# Generated by Django 5.2.5 on 2025-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.CharField()),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=10)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('adpi_response', models.TextField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
